////////////////////////////////////////////////////////////////////////////////
//
// metplus_ens.conf
// Starter probabilistic/ensemble seasonal verification
//
////////////////////////////////////////////////////////////////////////////////

[config]
PROCESS_LIST = EnsembleStat

[include]
file_1 = {env[EVS_SEASONAL_METPLUS_ROOT]}/common/base.conf
file_2 = {env[EVS_SEASONAL_METPLUS_ROOT]}/common/paths.conf
file_3 = {env[EVS_SEASONAL_METPLUS_ROOT]}/common/masks.conf
file_4 = {env[EVS_SEASONAL_METPLUS_ROOT]}/ens/EnsembleStat_fcstSEASONAL_obsANALYSIS.conf
