////////////////////////////////////////////////////////////////////////////////
//
// paths.conf - shared path conventions
//
////////////////////////////////////////////////////////////////////////////////

[dir]
FCST_DIR = {env[FCST_INPUT_DIR]}
OBS_DIR = {env[OBS_INPUT_DIR]}
CLIMO_DIR = {env[CLIMO_INPUT_DIR]:-}

TMP_DIR = {env[METPLUS_TMP_DIR]:-{env[METPLUS_OUT_DIR]}/tmp}
