////////////////////////////////////////////////////////////////////////////////
//
// metplus_det.conf
// Starter deterministic seasonal verification
//
////////////////////////////////////////////////////////////////////////////////

[config]
PROCESS_LIST = GridStat

# Include shared seasonal configs
[include]
file_1 = {env[EVS_SEASONAL_METPLUS_ROOT]}/common/base.conf
file_2 = {env[EVS_SEASONAL_METPLUS_ROOT]}/common/paths.conf
file_3 = {env[EVS_SEASONAL_METPLUS_ROOT]}/common/masks.conf
file_4 = {env[EVS_SEASONAL_METPLUS_ROOT]}/det/GridStat_fcstSEASONAL_obsANALYSIS.conf
